### PR TITLE
Patch vulnerabilities found in dependencies

### PR DESCRIPTION
**Pull request by JantsoP**
gjson
gjson
Bluemonday
bluemonday

### CODE REVIEW

**Comment by l-zeuch** [comment]
No PR to master :notlikethis:

**Comment by JantsoP** [comment]
Well it should be master since it's pretty much EVERY SINGLE yag instance out there. Mine is already secured.

**Comment by l-zeuch** [comment]
Fair enough - Jonas should be the judge of that I guess.

(Also just came to my mind that vulnerabilities should be fixed ASAP)

**Comment by jonas747** [comment]
Fixed these myself

**Pull request closed without merging**
