### PR TITLE
addition to clean command: flag minAge

### PR DESCRIPTION
**Pull request by mrbentarikau**
Users have requested this quit a lot, it works well in conjunction with other flags, only thing probably is the name of the flag : )

### CODE REVIEW

**Comment by jonas747** [comment]
Looks good, in hindsight the naming for the switches here is really bad, need to fix that, but for now call it "minage" instead since you're only removing 2 letters and adding a lot of cognitive load.

**Comment by mrbentarikau** [comment]
consistency sake, because clearviolations command has "mina" flag, shouldn't this be set here as well? Should I change back from minage to mina?

**Comment by jonas747** [comment]
Yeah it should be changed there aswell, ill have to imeplement a system for switches wchich keeps deprecated aliases working, so that stuff and people don't break.

**Comment by mrbentarikau** [comment]
roger that!

**Pull request merged**
