### PR TITLE
Update plugin_bot.go

### PR DESCRIPTION
**Pull request by buthed010203**
Moderation: Aliases, Caps, Spelling

### CODE REVIEW

**Comment by jonas747** [comment]
can you change "warnings are saved" to "warnings are saved on the bot"

**Comment by buthed010203** [comment]
@jonas747 Changed it to warnings are saved eith the bot

**Comment by jonas747** [comment]
remove the history alias aswell

**Comment by buthed010203** [comment]
@jonas747 done

**Pull request merged**
