### PR TITLE
Invite link blacklist (discordy.com)

### PR DESCRIPTION
**Pull request by CHamburr**

### CODE REVIEW

**Comment by CHamburr** [comment]
Sorry I deleted something by accident I got it back now

**Comment by jonas747** [comment]
Hm that still isn't working right, might be best to make a new regex for it instead of making this one hella complicated, ill have to think it it through, put this on hold for now.

**Comment by CHamburr** [comment]
Also include discordlist.me

**Comment by jonas747** [comment]
This system has changed now, and i have added this site.

**Pull request closed without merging**
