### PR TITLE
Typo fix guildunavilable.go

### PR DESCRIPTION
**Pull request by BlackWolfWoof**
Fixed typo (Thanks to Ewgene#0006 for bringing this to my attention)

### CODE REVIEW

**Comment by LemmeCry** [comment]
While you're at it, might also wanna change "wether" to "whether".

**Comment by BlackWolfWoof** [comment]
Wait... i hope that didn't break anything... if it did, sorry lol. I thought that button would delete the forked stuff aaa

**Comment by l-zeuch** [comment]
when it says "you can now safely delete", you can indeed safely delete.
I suggest forking again (aka deleting your old fork) and then keeping it up to date with
`git fetch upstream` and then `git merge upstream/dev` and `git merge upstream/master`, respectively.

**Comment by BlackWolfWoof** [comment]
I am on mobile...

**Comment by l-zeuch** [comment]
Then do it on PC :^)

**Comment by BlackWolfWoof** [comment]
Uhh so did i just break / revert shit? Like idk what i did or if i even did anything

**Comment by l-zeuch** [comment]
Nothing broke. Let's talk in the server though

**Pull request merged**
