### PR TITLE
Update question mark

### PR DESCRIPTION
**Pull request by arch-lord**
This is my first PR and it's quite trivial. I'm just changing the question mark icon to one that doesn't look like it was drawn by a 4-year-old.

### CODE REVIEW

**Comment by buthed010203** [comment]
The question mark is amazing and deserves praise.

**Comment by arch-lord** [comment]
@buthed010203 Thee old one or the new one?

**Comment by jonas747** [comment]
neat

**Comment by ACA30** [comment]
Since your PR was merged already, changes will apply on the next bot update, which will probably be around a week, however it could be sooner or it could be later. Thanks for your support!

**Pull request merged**
