### PR TITLE
cc: add ability to run interval commands from dash

### PR DESCRIPTION
**Pull request by jo3-l**
This adds the ability to run interval CCs immediately from the dashboard, as title states.
Mostly useful for testing (no need to wait for it to trigger / put it into another CC).
To prevent spam, there is a 5s cooldown -- let me know if you want this changed.

Image of main CC listing
Image of edit CC view
Second one looks particularly ugly but I couldn't find a better place to put it, suggestions are appreciated.

### CODE REVIEW

**Comment by MatiasMFM2001** [comment]
Here, button image would be 🔄 emoji. What do you think?
imagen
imagen

For your first screenshot, I think user may hit `Run now` and/or `Delete` buttons by accident, trying to click `Edit`. I suggest this:
imagen

**Comment by jo3-l** [comment]
1) 🔁 emoji feels too subtle to me to be honest.
2) That's a good idea, will switch around the order in a moment...

**Comment by jonas747** [comment]
This dosen't work when the webserver is not running on the same process as the bot itself, you should either make a pubsub that triggers on the bot side, or just set the next run time to immediately and update the scheduled event for it

**Review by jonas747 — CHANGES_REQUESTED** [review]
This dosen't work when the webserver is not running on the same process as the bot itself, you should either make a pubsub that triggers on the bot side, or just set the next run time to immediately and update the scheduled event for it

**Comment by jo3-l** [comment]
Switched to a pubsub event in https://github.com/jonas747/yagpdb/pull/896/commits/703d0fa9bacacd3dde6453304b067930262c530a, still works fine (as far as I can tell) but I haven't tested with the webserver/bot on different processes.

**Pull request merged**
