### PR TITLE
Tickets- Include ticket Title in transcripts

### PR DESCRIPTION
**Pull request by Satty9361**
It has been pointed out that finding a transcript using just the ticket number becomes difficult. Adding the ticket title in the filename would resolve this.

### CODE REVIEW

**Comment by jonas747** [comment]
Do you know the max length of the filename?

**Comment by jonas747** [comment]
Maybe limit it to say 30 chars, `using common.CutStringShort(s, len)`

**Comment by Satty9361** [comment]
Even stuff like this worked for me:
attachments-2-01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567-0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789.PNG
 so i dont think it should be an issue atleast with addition of channel name which has a limited size by itself. With the attachment name maybe some limit can be imposed.

**Comment by jonas747** [comment]
ah fair enough then

**Pull request merged**
