### PR TITLE
Modify timezone setting procedure to behave more properly, attempt two

### LINKED ISSUE #731: Undesired result for timezones with overlapping names
Hello,

After enabling timezone commands and conversion on my server, an interesting issue popped up. Specifically, when a user attempted to `setz America/Dawson`, they got the following response:

```
More than 1 result, reuse the command with a one of the following:
America/Dawson_Creek: MST
America/Dawson: PDT

Your current time zone is registered to: America/Denver MDT (UTC-6)
```

The issue here is clearly the overlapping timezone names. Can this be addressed somehow?

### PR DESCRIPTION
**Pull request by LRitzdorf**
This PR serves the same purpose as #761, but uses the proper feature branch as a base.

Formerly, if the user specified a zone name that's a subset of another one, no action would occur. For example, `setz America/Dawson` would inform the user that zones called `America/Dawson` and `America/Dawson_Creek` were available, but would not set the desired zone. See #731 for details.

Now, if multiple matching zones are available but one is an exact match, it will be set, while also informing the user that other matching zones are available.

Resolves #731

### CODE REVIEW

**Comment by LRitzdorf** [comment]
@jonas747 @Satty9361 It's been a while, and this simple fix hasn't been merged yet. I'd like to draw your attention here, if possible.
Thanks!

**Comment by mrbentarikau** [comment]
have you even tested the code? Looking at it... it will never solve your America/Dawson issue for example.

**Comment by LRitzdorf** [comment]
@mrbentarikau I have not, actually -- I lack the resources to run a full Discord bot. However, if someone else is able to test my edits, that would be greatly appreciated.

Also, I'm not terribly familiar with Go, so it's entirely possible that my changes might not solve the issue. Can you offer any tips as to what isn't working as intended?

**Comment by LRitzdorf** [comment]
Okay, that *should* work now. As noted previously, I can't confirm this myself, so any further evaluation would be greatly appreciated.

**Pull request closed without merging**
