### PR TITLE
Updated addReaction template

### PR DESCRIPTION
**Pull request by michelhn**
Added small explanation and link to https://unicode.org/Public/emoji/11.0/emoji-test.txt

### CODE REVIEW

**Comment by LoganK** [comment]
I'm pretty sure that if there is a fully-qualified and non-fully-qualified variant, it must be the *non*-fully-qualified variant. Feel tree to test and let me know if I'm wrong. (I was mostly testing with keycaps which perhaps behave differently?)

Also, I should just fix it to strip FEOF if found.

And add named emoji. :smile:

**Comment by LoganK** [comment]
https://github.com/jonas747/discordgo/pull/2

**Comment by LoganK** [comment]
Might be worth updating the template documentation to state that global emoji (Nitro) are not supported.

**Comment by jonas747** [comment]
So whats the status on this?

**Comment by michelhn** [comment]
Can be closed due to gitbook

**Pull request closed without merging**
