### PR TITLE
Update DM embed footer

### PR DESCRIPTION
**Pull request by l-zeuch**
This pull request fixes the weird formatting often observed in the embed of a direct message sent with `sendDM`, see the following screenshot.
image

Further, we utilize the footer icon to display the guild's icon.

This has been tested on a selfhosted instance and works just fine, as shown here:
image

As I am only a beginner (yet), I appreciate any feedback, as usual.

Thanks in advance!

### CODE REVIEW

**Comment by l-zeuch** [comment]
So I found out via #468 that the bold markdown was somewhat intended, so I updated that back to that.
Fixed the typo where "from" was capitalized, the guild icon is still in there.

**Comment by jonas747** [comment]
honestly cant remember why this was intended, so might aswell change it

**Comment by l-zeuch** [comment]
Alright, I'll push an update

**Comment by l-zeuch** [comment]
Ready for merge 😄

**Comment by jonas747** [comment]
👍

**Pull request merged**
