### PR TITLE
show server icon besides server name in server selection

### PR DESCRIPTION
**Pull request by Spongerooski**
suppose I have 2 servers with the same name but different icons, this helps differentiate between them.
plus, I think it looks better than just a simple wrench

I have tested this on a selfhost and it seems to work fine 😃

### CODE REVIEW

**Comment by l-zeuch** [comment]
+1 on this, I can see it adding a better experience with server navigation (I sometimes happen to misclick the server, an icon could help)

**Comment by jonas747** [comment]
Has this been tested on mobile?

**Comment by fluffyfirefly** [comment]
Seems to work as intended on mobile, tested with Firefox mobile on a selfhosted YAG instance.

**Comment by Spongerooski** [comment]
^, works fine on mobile
image

**Comment by Spongerooski** [comment]
Do you think it would be a better idea to show the question mark image instead of the wrench if a server has no icon?

**Comment by l-zeuch** [comment]
Would leave it as wrench to be fair, people are used to that now. 
A question mark *may* confuse users into thinking that their server is unavailable or something along the line of that.

**Pull request merged**
