### PR TITLE
Logs: Channel flag for log command

### PR DESCRIPTION
**Pull request by l-zeuch**
User suggestion, a channel flag for the log command.

Works fine on selfhost, as far as I can tell. Nothing much to explain on top of that 😄

### CODE REVIEW

**Comment by jonas747** [comment]
Hm we should have a check for whether they have access to the channel or not

**Review by jonas747 — CHANGES_REQUESTED** [review]
Hm we should have a check for whether they have access to the channel or not

**Comment by l-zeuch** [comment]
You're right, we should check that. Will push an update in a moment!

**Review by jonas747 — CHANGES_REQUESTED** [review]
We should also check the view channel and message history perms

**Comment by l-zeuch** [comment]
> We should also check the view channel and message history perms
Isn't `view_channel` implied through `read_messages`? 
Can't seem to find the constant for `view_channel` at https://pkg.go.dev/github.com/jonas747/discordgo@v1.5.6?utm_source=gopls#pkg-constants ...

I'll add the message history permission, still not quite sure about the view channel perm.

**Comment by jonas747** [comment]
You're right, i need to add it, i'm not 100% if it is implied or not but better be on the safe side of things and not make assumptions when working with discord.

**Comment by l-zeuch** [comment]
👍 lmk when you added it

**Pull request merged**
