### PR TITLE
delete Nicknames

### PR DESCRIPTION
**Pull request by mrbentarikau**
An idea-level PR - enabling user to delete their own nickname records from the guild. It either deletes all nicknames till the last one recorded or if user does not have any active nicknames then everything.

This is idea-level because I don't know the general plan on handling username/nickname recordings.

### CODE REVIEW

**Comment by jonas747** [comment]
Should probably be done in the control panel, in the user menu perhaps as a new entry "user data"

**Comment by mrbentarikau** [comment]
but that way regular users don't have access nor control over their nickname or even username data, if it's on control panel and tied to guild admins.

**Comment by jonas747** [comment]
it wouldn't be tied to a server, anyone can log in...

**Comment by jonas747** [comment]
same as the premium page

**Comment by mrbentarikau** [comment]
yes, I understand it now... hmm, will close this then.

**Pull request closed without merging**
