### PR TITLE
Update swearwords.go

### PR DESCRIPTION
**Pull request by MrKillMyself**

### CODE REVIEW

**Comment by NaruDevnote** [comment]
In what way is this PR beneficial? You removed almost half of the words.

**Comment by JordiHakimZiyech** [comment]
Yeah this is a useless PR.
if you don't want these words, make your own list using auto mod v2.

**Comment by Olde7325** [comment]
Please do not spam the repository with unnecessary PRs, if you want to "just test" please do so on your own, private repositories.
To add, please do not rush PRs to `master` / `main`.

As @NaruDevnote already said, in what way is it beneficial to remove almost half of the words which are supposed to be filtered?

**Comment by Jo3-L** [comment]
From CONTRIBUTING.md:
> push the changes you make to the dev branch

**Pull request closed without merging**
