### PR TITLE
Reddit: disable feeds option

### PR DESCRIPTION
**Pull request by mrbentarikau**
To disable and not just to delete a Reddit feed has been requested several times... Looking at the back end of reddit code, it looks like nothing dramatical needs to be changed; None/0 channels in database are already avoided and disabled. So this little change enables front-end possibility for users to disable their feed.

### CODE REVIEW

**Comment by Wolveric** [comment]
I feel like a command to toggle these setting from within Discord, would be a notable inclusion for this feature.

**Comment by mrbentarikau** [comment]
reddit is just totally outside of discord, only manageable through control panel

**Comment by Wolveric** [comment]
It's just I think enabling such functionality, would give the feature a greater use.

**Comment by mrbentarikau** [comment]
This all needs Jonas' opinion anyway because there are other ways to disable a feed, like a button : ) And how disabling a feed will affect the re-enabled one later on.

**Comment by l-zeuch** [comment]
-1 on a new command that's likely to be never used.
Control panel is fine.
> YAGPDB is nearly exclusively configured through its control panel. If you want to make any major configuration changes, you'll have to go through there.

: )

**Comment by jonas747** [comment]
Maybe add a check on the webserver to set the `disabled` field if it's 0, i know this happens somewhere down the line in mqueue or somwhere but this would be better IMO

**Comment by mrbentarikau** [comment]
> Maybe add a check on the webserver to set the `disabled` field if it's 0, i know this happens somewhere down the line in mqueue or somwhere but this would be better IMO

Currently it yeah goes automatically disabled if next post comes in and no channel is found.

**Comment by mrbentarikau** [comment]
I hope you meant something like this ^

**Comment by jonas747** [comment]
looks about right

**Comment by Wolveric** [comment]
> -1 on a new command that's likely to be never used.
> Control panel is fine.
> > YAGPDB is nearly exclusively configured through its control panel. If you want to make any major configuration changes, you'll have to go through there.
> 
> Feel like disabling a reddit feed is a major configuration.
Listen here you little-

**Pull request merged**
