### PR TITLE
Autorole update

### PR DESCRIPTION
**Pull request by buthed010203**
Updated autorole to show a disclaimer

### CODE REVIEW

**Comment by jonas747** [comment]
remove the ** or change them do <b> tags

**Comment by buthed010203** [comment]
@jonas747 done, idk if thats right but if its not you can change it cause i set it that way idk

**Comment by buthed010203** [comment]
xd clicked close

**Comment by jonas747** [comment]
Nah thats right

**Comment by buthed010203** [comment]
K

**Pull request merged**
